title:me 
description: My Personal Stack Problems
author: Jack Shipway
github: https://github.com/ShipJ
about: I am a data science enthusiast - interested in everything from , to sports betting.
urls:
    - text: About Me
      url: /about/
    - text: Github
      url: https://github.com/ShipJ
    - text: XML Feed
      url: /feed.xml
url: "https://jshippers.com"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown